spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:18080
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /order-service/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0

# db info
