CREATE SCHEMA IF NOT EXISTS USER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS ORDER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS PRODUCT_SCHEMA;
CREATE SCHEMA IF NOT EXISTS COMPANY_SCHEMA;
CREATE SCHEMA IF NOT EXISTS HUB_SCHEMA;
CREATE SCHEMA IF NOT EXISTS DELIVERY_SCHEMA;
CREATE SCHEMA IF NOT EXISTS DELIVERY_MANAGER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS SLACK_MESSAGE_SCHEMA;
